### ISSUE TITLE
Can't modify frozen String

### ISSUE THREAD

**Issue by tarnagas** [agardiner/arg-parser#1]
```
        2: from /var/lib/gems/2.5.0/gems/arg-parser-0.3.1/lib/arg-parser/definition.rb:386:in `show_help'
        1: from /var/lib/gems/2.5.0/gems/arg-parser-0.3.1/lib/arg-parser/definition.rb:386:in `each'
/var/lib/gems/2.5.0/gems/arg-parser-0.3.1/lib/arg-parser/definition.rb:392:in `block in show_help': can't modify frozen String (FrozenError)
```

Sample:

```
# frozen_string_literal: true

require 'arg-parser'

class MyClass
    include ArgParser::DSL

    keyword_arg :my_keyword_arg, 'This is a keyword arg; if not specified, returns value1',
        default: 'value1'
end
```

https://www.wyeworks.com/blog/2015/12/01/immutable-strings-in-ruby-2-dot-3/

**Comment by agardiner** [comment]
Thanks for the bug report! Fixed.
